name = input("Enter your name: ")
age = int(input("Enter your age: "))
gender = input("Enter your gender: ")
print("Your Name is: ", name)
print("your age is: ", age)
print("Your gender is: ", gender)
